### ISSUE TITLE
fillfalsy_backward error when backward-filling strings on windows

### ISSUE THREAD

**Issue by xliu2021** [InvestmentSystems/static-frame#427] opened 2022-01-20 20:16 UTC
**Description**

There is a `UnicodeDecodeError` when using `fillfalsy_backward` to backward-fill strings on Windows

**Example**
```python
s = sf.Series(["", "Not empty"])
s.fillfalsy_backward()

Out[37]: Traceback (most recent call last):
UnicodeDecodeError: 'utf-32-le' codec can't decode bytes in position 0-3: code point not in range(0x110000)
```

**Platform**
```python
Out[38]: 
<Series: platform>
<Index>
platform           Windows-10-10.0.18362-SP0
sys.version        3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 16:59:10) [MSC v.1916 64 bit (AMD64)]
static-frame       0.8.31
numpy              1.17.4
pandas             0.24.2
xlsxwriter         1.1.2
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.6.1
pyarrow            0.17.0
msgpack            <ModuleNotFoundError>
msgpack_numpy      <ModuleNotFoundError>
<<U13>             <object>
```

**Comment by flexatone** [comment] 2022-01-20 21:36
Many thanks for posting this issue. 

This appear to be an issue with the version of NumPy you are using (1.17.4). There is a NumPy issue that reproduces the same error, and appears to now be fixed.

https://github.com/numpy/numpy/issues/15363

I cannot reproduce the issue in my Windows tests which actually use NumPy 1.17.4

https://github.com/InvestmentSystems/static-frame/actions/runs/1725655180

Please try a more modern version of NumPy to see if that resolves the issue.

**Comment by xliu2021** [comment] 2022-01-21 00:23
Thank you for checking.

You are right. When I bump Numpy version to latest numpy-1.22.1, it fixed this issue

**Comment by flexatone** [comment] 2022-01-21 00:39
Great, thanks for testing this. I will close this issue but it might serve others well if they encounter the same issue.

**Closed by flexatone** 2022-01-21 00:39 UTC

**Comment by gettodaze** [comment] 2022-01-27 21:28
Just a note, I was able to reproduce on windows. I find it occurs with `fillfalsy_forward` as well, and does not occur with the object dtype. I am not seeing it occur with the `<U1` dtype.
