### ISSUE TITLE
Frame/Series with IndexDate has `.loc[[]]` raise

### ISSUE THREAD

**Issue by gettodaze** [InvestmentSystems/static-frame#454] opened 2022-04-07 22:41 UTC
**Description**

I notice that for frames and series with an `IndexDate`, `frame.loc[[]]` raises, whereas `iloc[[]]` passes. Also both pass for frames/series with `Index`.
| |.iloc[[]] |.loc[[]] |
|--|--|--|
|`Index` |Pass |Pass |
|`IndexDate`|Pass |Fail |

**Example**

Provide an interactive Python session, or Python code, to demonstrate the issue. Please keep example data to a minimum.

```python
sf.Series([1], index=sf.IndexDate.from_labels(['2020-01-01'])).loc[[]]
# TypeError: reduce() of empty sequence with no initial value
```

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
>>> import static_frame as sf
>>> sf.Platform.display()

<Series: platform>
<Index>
platform           Linux-5.4.0-107-generic-x86_64-with-glibc2.27
sys.version        3.8.12 (default, Mar 31 2022, 09:39:09) [GCC 7.5.0]
static-frame       0.8.38
numpy              1.17.4
pandas             0.24.2
xlsxwriter         1.1.5
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.6.1
pyarrow            0.17.0
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>
```

**Comment by flexatone** [comment] 2022-04-08 15:19
Many thanks for isolating this issue.

The root cause has to do with special handling for `datetime64` arrays and this peculiar fact: only in the case of an empty array is it possible to have an array that returns a "generic" unit: 

```python
>>> np.datetime_data(np.array([], dtype=np.datetime64).dtype)                                                                                                                                                                                        
('generic', 1)
```
Regardless, I found a better way to handle this by eagerly looking for an empty selection, which is an optimization that has broader benefits.

This fix will be in the 0.9.1 release.

**Closed** 2022-04-08 15:24 UTC
