### ISSUE TITLE
Frame.from_xlsx fails when reading single column xlsx sheets

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#139] opened 2019-12-04 21:09 UTC
Given the following xlsx (/tmp/tmp.xlsx):

![image](https://user-images.githubusercontent.com/3046190/70181591-064ffe80-1697-11ea-963f-67bb9a9a14bb.png)

```python
sf.Frame.from_xlsx('/tmp/tmp.xlsx')
```

Fails with the following:

```
  File "/home/rutherford/.env37/lib/python3.7/site-packages/static_frame/core/frame.py", line 1465, in from_xlsx
    dtypes=dtypes
  File "/home/rutherford/.env37/lib/python3.7/site-packages/static_frame/core/store_xlsx.py", line 339, in read
    name=name
  File "/home/rutherford/.env37/lib/python3.7/site-packages/static_frame/core/frame.py", line 502, in from_records
    own_columns=own_columns,
  File "/home/rutherford/.env37/lib/python3.7/site-packages/static_frame/core/frame.py", line 1764, in __init__
    row_count = len(self._index)
builtins.TypeError: object of type 'NoneType' has no len()
```

**Comment by ForeverWintr** [comment] 2019-12-04 21:11
Possibly related: the same sheet fails when used in a `Bus`, although with a different error:

```python
b = sf.Bus.from_xlsx('/tmp/tmp.xlsx')
b['Sheet1']
```

Produces:

```
  File "/home/rutherford/.env37/lib/python3.7/site-packages/static_frame/core/bus.py", line 248, in __getitem__
    return self._extract_loc(key)
  File "/home/rutherford/.env37/lib/python3.7/site-packages/static_frame/core/bus.py", line 222, in _extract_loc
    self._update_series_cache_iloc(key=iloc_key)
  File "/home/rutherford/.env37/lib/python3.7/site-packages/static_frame/core/bus.py", line 186, in _update_series_cache_iloc
    frame = self._store.read(label)
  File "/home/rutherford/.env37/lib/python3.7/site-packages/static_frame/core/store_xlsx.py", line 339, in read
    name=name
  File "/home/rutherford/.env37/lib/python3.7/site-packages/static_frame/core/frame.py", line 494, in from_records
    return cls(TypeBlocks.from_blocks(block_gen()),
  File "/home/rutherford/.env37/lib/python3.7/site-packages/static_frame/core/type_blocks.py", line 158, in from_blocks
    raise ErrorInitTypeBlocks('cannot derive a row_count from blocks; provide a shape reference')
static_frame.core.exception.ErrorInitTypeBlocks: cannot derive a row_count from blocks; provide a shape reference
```

**Comment by flexatone** [comment] 2019-12-08 16:08
Many thanks for isolating this issue. The first exposed a number of issues in both writing and reading XLSX without index and or columns. These changes will be part of the 0.5.7 release.

Please see the following tests that round-trip between examples similar to the one shown above.

https://github.com/InvestmentSystems/static-frame/blob/be4056d8d1e0a290c537cd562af24738e389e3a6/static_frame/test/unit/test_store_xlsx.py#L98

**Comment by ForeverWintr** [comment] 2019-12-17 23:50
@flexatone Thanks for the fix! However, the Bus issue is still occurring. I can open a separate issue if you'd like.

**Comment by flexatone** [comment] 2019-12-20 17:38
Thanks for the update. Here, the issue is that the  Bus is not exposing the opportunity to provide configuration for `index_depth`, `column_depth`. I will create a new issue to track the addition of that feature.

**Closed by flexatone** 2019-12-20 17:38 UTC
Labels: bug

**Comment by flexatone** [comment] 2019-12-30 15:12
In the 0.5.9 release, `StoreConfig` and `StoreConfigMap` objects are available to configure `Bus` reading and writing for multiple `Frames` over the life of the `Bus`. Here, you can set the appropriate `index_depth` to handle the single-column case you have isolated.

```python
>>> import static_frame as sf

>>> f1 = sf.Frame.from_dict(dict(a=(1,2,3)), index=('x', 'y', 'z'), name='f1')
>>> config = sf.StoreConfig(include_index=True, index_depth=1)

>>> b1 = sf.Bus.from_frames((f1,), config=config)
>>> b1.to_xlsx('/tmp/tmp.xlsx')

>>> b2 = sf.Bus.from_xlsx('/tmp/tmp.xlsx', config=config)
>>> b2['f1']
<Frame: f1>
<Index>     a       <<U1>
<Index>
x           1
y           2
z           3
<<U1>       <int64>
