### ISSUE TITLE
sf.Index.union hangs when given a large number of NaN values

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#242] opened 2020-09-03 20:03 UTC
Here is a easily reproducible example of what the title refers to.
```python
>>> s = sf.Series([1.01] + [np.nan] * 1_000_00)
>>> s.index.union(s, s) # This will hang indefinitely, and cannot be killed with Ctrl^C
```

Investigating, I realized a few things. Series will by default iterate over their indices, not values This is why I thought the above code would work. However, `sf.Index.union`, when given a series, will iterate over its _values_, not it's index. I believe this is part of the reason why my code gets stuck, because NaN != NaN (I can only reproduce this when the series contain many NaN values).

The part that is weird to me, is that it was never able to finish building this new index object, and it was unkillable using `Ctrl^C`.

A few observations:
1) It's a bit surprising to me that `sf.Index.union` will iterate over a series' values, instead of the default. To me, this breaks the principle of least surprise.
2) I think there's probably room for optimizing how the union process is happening, given the fact my code will get it into a state where it can't be interuppted with `Ctrl^C`
3) I think that in the context of an index, NaN == NaN should either be True by default, or disallowed entirely as key. (I strongly prefer the first option).
a) I think there is precedent for this, as this is illegal: `sf.Index([1] + [np.nan]*2)`. Also, if NaN == NaN is False by default in an index, then it would be impossible to key into it using NaN, since the key would never be found.

Here's a example of what will happens with when I run the first code snippet with a much smaller number of NaNs.
```python
>>> s = sf.Series([1.01] + [np.nan] * 2)
>>> s.index.union(s, s) # I think this result is illegal, since there are multiple NaNs in the index
<Index>
0.0
1.0
1.01
2.0
3.0
nan
nan
nan
nan
<float64>
```

My expectation is that we would see one of the two following results:
```python
# Example 1:
>>> s.index.union(s, s) # This was my original expectation, where it iterates a Series' index by default, not its values
<Index>
1
2
3
<int64>

# Example 2:
>>> s.index.union(s, s) # Even if union still iterates the values by default, NaN == NaN should be True in the context of an index
<Index>
0.0
1.0
1.01
2.0
3.0
nan
<float64>

# NOTE: Preferrably Example 2 would be called like this...
>>> s.index.union(s.values, s.values) # This is the combination of my two main suggestions
<Index>
0.0
1.0
1.01
2.0
3.0
nan
<float64>
```

**Comment by flexatone** [comment] 2020-09-03 22:00
Many thanks for posting this issue. There are number of sub-issues in here to address, which sill take some time.

I do agree, at least initially, that a `Series` passed to an `Index.union` should either fail or represent itself as an iterable of labels. Using `.values`, as is required with `Index.isin` is probably the best approach. This will need to be part of the 0.7 changes.

I will investigate the performance issue separately.

**Comment by chaburkland** [comment] 2020-09-03 22:04
Thanks!

I'm curious what your thoughts are about how `Index.union` can be used to create an index with multiple NaN values, whereas you can't achieve the same index through normal `Index` construction?

**Comment by flexatone** [comment] 2020-09-06 13:06
I have moved the issue regarding multiple NaNs to #245, and have renamed this to focus on the union performance issue.

**Comment by flexatone** [comment] 2020-09-06 20:20
In regard to the performance issue: I have added special handling to look for and remove multiple NaNs that persist after a union. The root cause of this issue is in `np.union1d` (see #245), which will not always identify NaNs as identical. With this change the performance of the union shown above is reasonable.

```python 
In [5]: s1 = sf.Series([1.01] + [np.nan] * 1_000_00)                                                                               

In [6]: %timeit s1.index.union(s1, s1)                                                                                             
25.7 ms ± 257 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by flexatone** [comment] 2020-09-06 20:24
Thanks again for point out these issues; I will close this issue for now, as additional issues have been created for the change to `Index.union()` and the possibility of creating `Index` with multiple NaN. If you would like to propose disallowing NaN in `Index` entirely (which might be advisable given #245), please create a new issue.

**Comment by flexatone** [comment] 2020-09-08 20:52
I have isolated the performance issue here is specifically due to the unique behavior of putting NaNs in mappings. For both `dict` and `AutoMap`, loading a mapping of NaN instances is vastly slower than loading other types.

```python
In [11]: a1 = np.arange(10000)                                                                                                     

In [12]: a2 = np.full(10000, np.nan)                                                                                               

In [13]: %timeit automap.AutoMap(a1)                                                                                               
557 µs ± 1.17 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [14]: %timeit automap.AutoMap(a2)                                                                                               
1.57 s ± 58.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [15]: %timeit dict.fromkeys(a1)                                                                                                 
757 µs ± 34.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [16]: %timeit dict.fromkeys(a2)                                                                                                 
1.43 s ± 38.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Closed by flexatone** 2020-09-08 20:52 UTC
Labels: performance
