### ISSUE TITLE
binary operations between Frame and Series don't preserve column order

### ISSUE THREAD

**Issue by nekobon** [InvestmentSystems/static-frame#88] opened 2019-07-27 00:36 UTC
Frame <operation> Series changes column order even when both frame and series have the same order.

```python
In [40]: f = sf.Frame(1, columns=['dog', 3, 'bat'], index=[1, 2])                                                                               

In [41]: f                                                                                                                                      
Out[41]: 
<Frame>
<Index> dog     3       bat     <object>
<Index>
1       1       1       1
2       1       1       1
<int64> <int64> <int64> <int64>

In [42]: f.sum()                                                                                                                                
Out[42]: 
<Series>
<Index>
dog      2
3        2
bat      2
<object> <int64>

In [43]: f / f.sum()                                                                                                                            
Out[43]: 
<Frame>
<Index> bat       3         dog       <object>
<Index>
1       0.5       0.5       0.5
2       0.5       0.5       0.5
<int64> <float64> <float64> <float64>
```

Columns in the last Frame are expected to be **[`dog`, 3, `bat`]** in this order.

**Comment by flexatone** [comment] 2019-08-01 23:28
Many thanks for posting this issue.

The root cause of this behavior was in `Index.union()`, which was not taking the opportunity to compare indices before calling NumPy union functions. Now, if indices are equal, the same ordering is retained. In addition to `Index.union()`, `Index.intersection()` has been similarly improved.

This change will be pushed shortly and will be included in the 0.3.8 release.

**Closed** 2019-08-01 23:29 UTC
Labels: BUG
