### ISSUE TITLE
Assigning NumPy string to Frame with "U6" arrays raises UnicodeDecodeError on display

### ISSUE THREAD

**Issue by MARALB83** [InvestmentSystems/static-frame#444] opened 2022-03-04 02:06 UTC
**Description**

Assigning a numpy string to a Frame column of type string raises a UnicodeDecodeError.

**Example**

```python
import static_frame as sf
import numpy as np
x = sf.Frame(np.arange(25).reshape(5,5))
x = x.astype("U6")
s = "C840V0840"
ns = np.str_(s)
x.assign[0](ns)
Out[9]: Traceback (most recent call last):
  File "C:\Anaconda3\envs\ra_platform-20220303\lib\site-packages\IPython\core\formatters.py", line 224, in catch_format_error
    r = method(self, *args, **kwargs)
  File "C:\Anaconda3\envs\ra_platform-20220303\lib\site-packages\IPython\core\formatters.py", line 702, in __call__
    printer.pretty(obj)
  File "C:\Anaconda3\envs\ra_platform-20220303\lib\site-packages\IPython\lib\pretty.py", line 394, in pretty
    return _repr_pprint(obj, self, cycle)
  File "C:\Anaconda3\envs\ra_platform-20220303\lib\site-packages\IPython\lib\pretty.py", line 700, in _repr_pprint
    output = repr(obj)
  File "C:\Anaconda3\envs\ra_platform-20220303\lib\site-packages\static_frame\core\container.py", line 59, in __repr__
    return repr(self.display())
  File "C:\Anaconda3\envs\ra_platform-20220303\lib\site-packages\static_frame\core\frame.py", line 4177, in display
    return Display.from_params(
  File "C:\Anaconda3\envs\ra_platform-20220303\lib\site-packages\static_frame\core\display.py", line 550, in from_params
    d.extend_iterable(column, header=header_column)
  File "C:\Anaconda3\envs\ra_platform-20220303\lib\site-packages\static_frame\core\display.py", line 864, in extend_iterable
    for idx, value in enumerate(value_gen(), start=row_idx_start):
UnicodeDecodeError: 'utf-32-le' codec can't decode bytes in position 0-3: code point not in range(0x110000)
```

**Platform**
```python
>>> import static_frame as sf
>>> sf.Platform.display()
<Series: platform>
<Index>
platform           Windows-10-10.0.19041-SP0
sys.version        3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 16:59:10) [MSC v.1916 64 bit (AMD64)]
static-frame       0.8.35
numpy              1.17.4
pandas             0.24.2
xlsxwriter         1.1.2
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.6.1
pyarrow            0.17.0
msgpack            <ModuleNotFoundError>
msgpack_numpy      <ModuleNotFoundError>
<<U13>             <object>
```

**Comment by ForeverWintr** [comment] 2022-03-04 17:40
Just a note: This looks like it's actually raised by `repr`, not the assignment.

**Comment by chaburkland** [comment] 2022-03-04 17:46
@ForeverWintr I thought the same thing, but when I actually explored the underlying bytes across platforms, there were different, with Windows having very "strang"  bytes (e.g. `0x/*Q`) and Linux having "normal" bytes (`0x00A`)

**Comment by flexatone** [comment] 2022-03-04 18:42
Many thanks for posting this issue.

I believe this issue is related to the following, and that the root cause is due to the NumPy version you are using (1.17.4).
https://github.com/InvestmentSystems/static-frame/issues/200.
https://github.com/numpy/numpy/issues/15363

As I cannot reproduce this issue on Linux, @MARALB83, can you please try an ad-hoc test on Windows with NumPy 1.20.3 or later?

**Comment by MARALB83** [comment] 2022-03-05 00:40
@flexatone The assignment works with numpy 1.21.2.

**Comment by flexatone** [comment] 2022-03-05 01:13
Thanks, @MARALB83 ,  for checking! I will close this issue as the fix is upgrading NumPy.

**Closed by flexatone** 2022-03-05 01:13 UTC
