### ISSUE TITLE
Frame.set_index_hierarchy: add "sort_hierarchable" parameter

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#113] opened 2019-10-14 23:17 UTC
This may have been discussed before, but currently it is an error to set an index hierarchy on a `Frame` if the values destined for the index are in the wrong order:

```python
>>> f = sf.Frame([[2, 3, 4], [1, 2, 3], [2, 5, 4]], columns=('a', 'b', 'c'))
>>> f
<Frame>
<Index> a       b       c       <<U1>
<Index>
0       2       3       4
1       1       2       3
2       2       5       4
<int64> <int64> <int64> <int64>
>>> f.set_index_hierarchy(('a', 'b')) # raises static_frame.core.exception.ErrorInitIndex
```

This seems to have to do with an order dependency when constructing the index hierarchy, and can be resolved by sorting the frame before setting the index. Is this behaviour desired?

**Comment by flexatone** [comment] 2019-10-15 00:52
Thanks for posting this issue!

The issue is that StaticFrame uses a strict tree structure for `IndexHierarchy`, where each parent node can only be defined once. This is because StaticFrame uses `Index` objects to build `IndexHierarchy`, and `Index` objects are ordered and do not permit duplicates. 

For example, the following IH is fine, as the outer-most level can be defined as an `Index` of (2, 1):

```python
>>> sf.IndexHierarchy.from_labels([(2, 3), (2, 5), (1, 2)])
<IndexHierarchy>
2                3
2                5
1                2
<int64>          <int64>
```

Yet the following IH is invalid, as the implied outer `Index` level is (2, 1, 2), which is an invalid `Index`.

```python
>>> sf.IndexHierarchy.from_labels([(2, 3), (1, 2), (2, 5)])
Traceback (most recent call last):
static_frame.core.exception.ErrorInitIndex: invalid tree-form for IndexHierarchy: 2 in (2, 5) cannot follow 1 when 2 has already been defined.
```

Again, this is an artifact of building `IndexHierarchy` out of `Index` (thus the name!). Permitting otherwise would require a very different implementation of `IndexHierarchy`. At this time, using `Index` to build `IndexHierarchy` seems to provide more benefits than supporting arbitrary unique labels.

I will close this issue for now, but thanks for raising this question.

**Comment by ForeverWintr** [comment] 2019-10-15 16:34
Thanks for the response!

My intent was to discuss the mechanism for creating an index hierarchy using `set_index_hierarchy`, rather than the implementation of index hierarchy itself. 

It seems we cannot be sure that the method will succeed unless the frame is first sorted. Consider a case where the data used for development coincidentally fits the requirements for index hierarchy creation, but at some later date production data contains an invalid ordering. Should `set_index_hierarchy` sort the frame automatically? Should if fail if the frame is not sorted? Should we add a note to the documentation explaining the issue? I'm not sure which approach is best.

**Comment by flexatone** [comment] 2019-10-28 17:11
Thanks for these thoughts: you have nicely laid out the constraints of `IndexHierarchy`. I agree with the necessity of documenting hierarchability, and providing a utility method to sort in the necessary manner (or perhaps just a Boolean parameter to `set_index_hierarchy`.

Much of this work is already done in `IndexHierarchy.rehierarch`, which does a lexical sort of two or more columns, where the order is determined by the the order of first usage (rather than a strict sort).

As I do not think that sorting by hierarchability has general utility, what about a `sort_hierarchable` parameter to the `Frame.set_index_hierarchy`?

**Comment by flexatone** [comment] 2019-11-02 00:18
This has been implemented as a `sort` Boolean parameter to `Frame.set_index_hierarchy`. Note that the `sort` option defines the final order as the order of first observed, reusing the same approach as implemented in the `rehierarch` methods.

This will be available in 0.5, to be released this weekend.

```python
>>> import static_frame as sf
>>> records = (
...                 (1, 'a', 10),
...                 (2, 'c', 60),
...                 (1, 'c', 30),
...                 (2, 'a', 40),
...                 (2, 'b', 50),
...                 (1, 'b', 20),
...                 )
>>> f = sf.Frame.from_records(records)
>>> f.set_index_hierarchy([0, 1], drop=True, sort=True)
<Frame>
<Index>                           2       <int64>
<IndexHierarchy: (0, 1)>
1                        a        10
1                        c        30
1                        b        20
2                        a        40
2                        c        60
2                        b        50
<object>                 <object> <int64>
```

**Closed by flexatone** 2019-11-02 00:18 UTC
Labels: feature

**Comment by brandtbucher** [comment] 2019-11-02 05:29
I wonder if `sort` could be named better; I would assume that it actually *sorts* the values, rather than the first-seen ordering here here.

Perhaps `reorder`, `regroup`, or `cascade`?

**Comment by flexatone** [comment] 2019-11-02 13:05
Agreed. I was attracted to the brevity of `sort`, but it is potentially confusing. I have renamed the parameter `reorder_for_hierarchy`.
